### ISSUE TITLE
Issues while testing Alloyv2 branch

### ISSUE THREAD

**Issue by ricardoalcocer** [appcelerator-developer-relations/Sample.Mapping#32]
**On Android device**

If you run the app right after booting up the device, you get multiple crashes, until it finally launches and tells you "Could not reverse geocode the position".  After you get this error, the app can be launched and used as expected.  This is probably because the location services are not yet available to the app.

**Comment by FokkeZB** [comment]
@ricardoalcocer what Android version?

On Android 6 I get this error in the logs but the app does not crash:

```
[ERROR] GeolocationModule: (KrollRuntimeThread) [220,369] Location permissions missing
```

**Comment by FokkeZB** [comment]
I forgot to add run-time permissions. Can you check again? Just pushed that to the branch.
