### ISSUE TITLE
Invalid GUID- please advise

### ISSUE THREAD

**Issue by Cherese** [appcelerator-developer-relations/Sample.Mapping#34]
When I try to run the app, Appecelerator wants me to register the app. the GUID is invalid.

Please advise what I can do to fix this

Thank you

**Comment by ashcoding** [comment]
You can create a normal app. And then copy the values from that new app's tiapp.xml into this sample app for testing purposes.

**Comment by jasonkneen** [comment]
If you build the project, you can build the project and you'll be told the GUID is invalid and given a choice of GUIDS to use -- just swap in and rebuild.

**Comment by kakarot1991** [comment]
lmù:;:
